### ISSUE TITLE
Remote provisioning of EC2 server fails on TASK [common/git : Add git apt repo]

### ISSUE THREAD

**Issue by KenEucker** [solid-stack/ansible-ubuntu#3]
"The async task did not return valid JSON: No JSON object could be decoded"

removing the following like from /common/git/tasks/main.yml solved my provisioning issues

`async: 1800`

**Comment by pajtai** [comment]
I don't understand why sync, but not async would work.

Would you include the stdout / err for both?

**Comment by KenEucker** [comment]
https://gist.github.com/KenEucker/f52e013defa969932d3c168ccee215d1

This includes the error output for async.

**Comment by pajtai** [comment]
Closing as this looks like a connection issue unrelated to this npm.
