### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by Duder-onomy** [solid-stack/ansible-ubuntu#8]
On the base ubuntu 16.04 Amazon Machine Image on EC2, Python3 is installed. 
`ubuntu-xenial-16.04-amd64-server-20161020 (ami-a9d276c9)`

This creates some issues:

* Ansible must be on 2.2 or greater: [here](http://docs.ansible.com/ansible/python_3_support.html)
* When running commands Ansible must run with the correct interpreter on the managed node,
  Something like: 
`ansible-playbook sample-playbook.yml -e 'ansible_python_interpreter=/usr/bin/python3'`
This is an issue on the 16.04 because by default this distribution has a few python installations. On a fresh ec2 instance when attempting to enter the python repl you get:
```
ubuntu@ip-xxx-xx-xx-xx:~$ python
The program 'python' can be found in the following packages:
 * python-minimal
 * python3
```

**Comment by pajtai** [comment]
Version 2.0.0+ is ubuntu 16 compatible
